//
//  CircleBarStyleKit.swift
//  vMail
//
//  Created by Denis Lavrov on 17/03/16.
//  Copyright (c) 2016 bahus. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class CircleBarStyleKit : NSObject {

    //// Drawing Methods

    public class func drawBar(frame frame: CGRect = CGRectMake(21, 11, 414, 92)) {
        //// Color Declarations
        let whiteElement = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)
        var whiteElementRedComponent: CGFloat = 1,
            whiteElementGreenComponent: CGFloat = 1,
            whiteElementBlueComponent: CGFloat = 1
        whiteElement.getRed(&whiteElementRedComponent, green: &whiteElementGreenComponent, blue: &whiteElementBlueComponent, alpha: nil)

        let whiteTransparent = whiteElement.colorWithAlphaComponent(0.8)
        let whiteElement2 = UIColor(red: (whiteElementRedComponent * 0.8), green: (whiteElementGreenComponent * 0.8), blue: (whiteElementBlueComponent * 0.8), alpha: (CGColorGetAlpha(whiteElement.CGColor) * 0.8 + 0.2))

        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(frame.minX + 251.73, frame.minY + 42))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 414, frame.minY + 42))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 414, frame.minY + 92))
        bezierPath.addLineToPoint(CGPointMake(frame.minX, frame.minY + 92))
        bezierPath.addLineToPoint(CGPointMake(frame.minX, frame.minY + 42))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 162.27, frame.minY + 42))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 165.2, frame.minY + 30.31), controlPoint1: CGPointMake(frame.minX + 162.73, frame.minY + 37.91), controlPoint2: CGPointMake(frame.minX + 163.73, frame.minY + 33.99))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 207, frame.minY + 2), controlPoint1: CGPointMake(frame.minX + 171.83, frame.minY + 13.72), controlPoint2: CGPointMake(frame.minX + 188.05, frame.minY + 2))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 251.73, frame.minY + 42), controlPoint1: CGPointMake(frame.minX + 230.16, frame.minY + 2), controlPoint2: CGPointMake(frame.minX + 249.24, frame.minY + 19.5))
        bezierPath.closePath()
        whiteTransparent.setFill()
        bezierPath.fill()
        whiteElement2.setStroke()
        bezierPath.lineWidth = 1
        bezierPath.stroke()
    }

    public class func drawButton(frame frame: CGRect = CGRectMake(5, 6, 83, 83), highlighted: Bool = true) {
        //// Color Declarations
        let redRecord = UIColor(red: 1.000, green: 0.370, blue: 0.370, alpha: 1.000)
        var redRecordRedComponent: CGFloat = 1,
            redRecordGreenComponent: CGFloat = 1,
            redRecordBlueComponent: CGFloat = 1
        redRecord.getRed(&redRecordRedComponent, green: &redRecordGreenComponent, blue: &redRecordBlueComponent, alpha: nil)

        let redDim = UIColor(red: (redRecordRedComponent * 0.7), green: (redRecordGreenComponent * 0.7), blue: (redRecordBlueComponent * 0.7), alpha: (CGColorGetAlpha(redRecord.CGColor) * 0.7 + 0.3))
        let blueRecord = UIColor(red: 0.000, green: 0.611, blue: 1.000, alpha: 1.000)
        var blueRecordRedComponent: CGFloat = 1,
            blueRecordGreenComponent: CGFloat = 1,
            blueRecordBlueComponent: CGFloat = 1
        blueRecord.getRed(&blueRecordRedComponent, green: &blueRecordGreenComponent, blue: &blueRecordBlueComponent, alpha: nil)

        let blueDim = UIColor(red: (blueRecordRedComponent * 0.8), green: (blueRecordGreenComponent * 0.8), blue: (blueRecordBlueComponent * 0.8), alpha: (CGColorGetAlpha(blueRecord.CGColor) * 0.8 + 0.2))
        let whiteElement = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)

        //// Variable Declarations
        let highlightedColor = highlighted ? blueRecord : redRecord
        let highlightedStroke = highlighted ? blueDim : redDim


        //// Subframes
        let group2: CGRect = CGRectMake(frame.minX + floor(frame.width * 0.30361 + 0.3) + 0.2, frame.minY + floor(frame.height * 0.18675 + 0.1) + 0.4, floor(frame.width * 0.69199 + 0.07) - floor(frame.width * 0.30361 + 0.3) + 0.23, floor(frame.height * 0.80241) - floor(frame.height * 0.18675 + 0.1) + 0.1)


        //// Oval Drawing
        let ovalPath = UIBezierPath(ovalInRect: CGRectMake(frame.minX + floor(frame.width * 0.01807) + 0.5, frame.minY + floor(frame.height * 0.01807) + 0.5, floor(frame.width * 0.98193) - floor(frame.width * 0.01807), floor(frame.height * 0.98193) - floor(frame.height * 0.01807)))
        highlightedColor.setFill()
        ovalPath.fill()
        highlightedStroke.setStroke()
        ovalPath.lineWidth = 1
        ovalPath.stroke()


        //// Group 2
        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(group2.minX + 0.79383 * group2.width, group2.minY + 0.47867 * group2.height))
        bezierPath.addCurveToPoint(CGPointMake(group2.minX + 0.75168 * group2.width, group2.minY + 0.59716 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.79383 * group2.width, group2.minY + 0.52133 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.78680 * group2.width, group2.minY + 0.55924 * group2.height))
        bezierPath.addCurveToPoint(CGPointMake(group2.minX + 0.53390 * group2.width, group2.minY + 0.68246 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.70250 * group2.width, group2.minY + 0.64929 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.63225 * group2.width, group2.minY + 0.67773 * group2.height))
        bezierPath.addCurveToPoint(CGPointMake(group2.minX + 0.23885 * group2.width, group2.minY + 0.53081 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.39340 * group2.width, group2.minY + 0.69194 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.26695 * group2.width, group2.minY + 0.62559 * group2.height))
        bezierPath.addCurveToPoint(CGPointMake(group2.minX + 0.23183 * group2.width, group2.minY + 0.48815 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.23183 * group2.width, group2.minY + 0.51659 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.23183 * group2.width, group2.minY + 0.50237 * group2.height))
        bezierPath.addCurveToPoint(CGPointMake(group2.minX + 0.23183 * group2.width, group2.minY + 0.17536 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.23183 * group2.width, group2.minY + 0.38389 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.23183 * group2.width, group2.minY + 0.27962 * group2.height))
        bezierPath.addCurveToPoint(CGPointMake(group2.minX + 0.40745 * group2.width, group2.minY + 0.00948 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.23183 * group2.width, group2.minY + 0.10427 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.30910 * group2.width, group2.minY + 0.03318 * group2.height))
        bezierPath.addCurveToPoint(CGPointMake(group2.minX + 0.49175 * group2.width, group2.minY + 0.00000 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.43555 * group2.width, group2.minY + 0.00474 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.46365 * group2.width, group2.minY + 0.00000 * group2.height))
        bezierPath.addCurveToPoint(CGPointMake(group2.minX + 0.53390 * group2.width, group2.minY + 0.00000 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.50580 * group2.width, group2.minY + 0.00000 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.51985 * group2.width, group2.minY + 0.00000 * group2.height))
        bezierPath.addCurveToPoint(CGPointMake(group2.minX + 0.57605 * group2.width, group2.minY + 0.00474 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.54795 * group2.width, group2.minY + 0.00000 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.56200 * group2.width, group2.minY + 0.00000 * group2.height))
        bezierPath.addCurveToPoint(CGPointMake(group2.minX + 0.78680 * group2.width, group2.minY + 0.16588 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.69548 * group2.width, group2.minY + 0.02370 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.77275 * group2.width, group2.minY + 0.08531 * group2.height))
        bezierPath.moveToPoint(CGPointMake(group2.minX + 0.66738 * group2.width, group2.minY + 0.15166 * group2.height))
        bezierPath.addCurveToPoint(CGPointMake(group2.minX + 0.51283 * group2.width, group2.minY + 0.07109 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.66035 * group2.width, group2.minY + 0.10900 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.57605 * group2.width, group2.minY + 0.07109 * group2.height))
        bezierPath.addCurveToPoint(CGPointMake(group2.minX + 0.35828 * group2.width, group2.minY + 0.14692 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.44258 * group2.width, group2.minY + 0.07109 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.36530 * group2.width, group2.minY + 0.10900 * group2.height))
        bezierPath.addCurveToPoint(CGPointMake(group2.minX + 0.40043 * group2.width, group2.minY + 0.14692 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.37233 * group2.width, group2.minY + 0.14692 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.38638 * group2.width, group2.minY + 0.14692 * group2.height))
        bezierPath.addCurveToPoint(CGPointMake(group2.minX + 0.43555 * group2.width, group2.minY + 0.15640 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.41448 * group2.width, group2.minY + 0.14692 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.42150 * group2.width, group2.minY + 0.15166 * group2.height))
        bezierPath.addCurveToPoint(CGPointMake(group2.minX + 0.45663 * group2.width, group2.minY + 0.19905 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.45663 * group2.width, group2.minY + 0.16588 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.46365 * group2.width, group2.minY + 0.18483 * group2.height))
        bezierPath.addCurveToPoint(CGPointMake(group2.minX + 0.40043 * group2.width, group2.minY + 0.22275 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.44258 * group2.width, group2.minY + 0.21327 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.42853 * group2.width, group2.minY + 0.22275 * group2.height))
        bezierPath.addCurveToPoint(CGPointMake(group2.minX + 0.34423 * group2.width, group2.minY + 0.22275 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.37935 * group2.width, group2.minY + 0.22275 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.36530 * group2.width, group2.minY + 0.22275 * group2.height))
        bezierPath.addCurveToPoint(CGPointMake(group2.minX + 0.34423 * group2.width, group2.minY + 0.26066 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.34423 * group2.width, group2.minY + 0.23697 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.34423 * group2.width, group2.minY + 0.24645 * group2.height))
        bezierPath.addCurveToPoint(CGPointMake(group2.minX + 0.40043 * group2.width, group2.minY + 0.26066 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.36530 * group2.width, group2.minY + 0.26066 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.37935 * group2.width, group2.minY + 0.26066 * group2.height))
        bezierPath.addCurveToPoint(CGPointMake(group2.minX + 0.44960 * group2.width, group2.minY + 0.28436 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.42150 * group2.width, group2.minY + 0.26066 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.44258 * group2.width, group2.minY + 0.27014 * group2.height))
        bezierPath.addCurveToPoint(CGPointMake(group2.minX + 0.40043 * group2.width, group2.minY + 0.33649 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.46365 * group2.width, group2.minY + 0.30806 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.43555 * group2.width, group2.minY + 0.33175 * group2.height))
        bezierPath.addCurveToPoint(CGPointMake(group2.minX + 0.34423 * group2.width, group2.minY + 0.33649 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.37935 * group2.width, group2.minY + 0.33649 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.36530 * group2.width, group2.minY + 0.33649 * group2.height))
        bezierPath.addCurveToPoint(CGPointMake(group2.minX + 0.34423 * group2.width, group2.minY + 0.37441 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.34423 * group2.width, group2.minY + 0.35071 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.34423 * group2.width, group2.minY + 0.36019 * group2.height))
        bezierPath.addCurveToPoint(CGPointMake(group2.minX + 0.68143 * group2.width, group2.minY + 0.37441 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.45663 * group2.width, group2.minY + 0.37441 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.56903 * group2.width, group2.minY + 0.37441 * group2.height))
        bezierPath.addCurveToPoint(CGPointMake(group2.minX + 0.68143 * group2.width, group2.minY + 0.33649 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.68143 * group2.width, group2.minY + 0.36019 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.68143 * group2.width, group2.minY + 0.35071 * group2.height))
        bezierPath.addCurveToPoint(CGPointMake(group2.minX + 0.62523 * group2.width, group2.minY + 0.33649 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.66035 * group2.width, group2.minY + 0.33649 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.64630 * group2.width, group2.minY + 0.33649 * group2.height))
        bezierPath.addCurveToPoint(CGPointMake(group2.minX + 0.57605 * group2.width, group2.minY + 0.31754 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.60415 * group2.width, group2.minY + 0.33649 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.58308 * group2.width, group2.minY + 0.33175 * group2.height))
        bezierPath.addCurveToPoint(CGPointMake(group2.minX + 0.62523 * group2.width, group2.minY + 0.26540 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.55498 * group2.width, group2.minY + 0.29384 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.58308 * group2.width, group2.minY + 0.26540 * group2.height))
        bezierPath.addCurveToPoint(CGPointMake(group2.minX + 0.68143 * group2.width, group2.minY + 0.26540 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.64630 * group2.width, group2.minY + 0.26540 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.66035 * group2.width, group2.minY + 0.26540 * group2.height))
        bezierPath.addCurveToPoint(CGPointMake(group2.minX + 0.68143 * group2.width, group2.minY + 0.22749 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.68143 * group2.width, group2.minY + 0.25118 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.68143 * group2.width, group2.minY + 0.24171 * group2.height))
        bezierPath.addCurveToPoint(CGPointMake(group2.minX + 0.62523 * group2.width, group2.minY + 0.22749 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.66035 * group2.width, group2.minY + 0.22749 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.64630 * group2.width, group2.minY + 0.22749 * group2.height))
        bezierPath.addCurveToPoint(CGPointMake(group2.minX + 0.56903 * group2.width, group2.minY + 0.18957 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.59010 * group2.width, group2.minY + 0.22749 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.56903 * group2.width, group2.minY + 0.20853 * group2.height))
        bezierPath.addCurveToPoint(CGPointMake(group2.minX + 0.62523 * group2.width, group2.minY + 0.15166 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.56903 * group2.width, group2.minY + 0.17062 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.59010 * group2.width, group2.minY + 0.15166 * group2.height))
        bezierPath.addCurveToPoint(CGPointMake(group2.minX + 0.66738 * group2.width, group2.minY + 0.15166 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.63928 * group2.width, group2.minY + 0.15166 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.65333 * group2.width, group2.minY + 0.15166 * group2.height))
        bezierPath.closePath()
        bezierPath.miterLimit = 4;

        whiteElement.setFill()
        bezierPath.fill()


        //// Bezier 2 Drawing
        let bezier2Path = UIBezierPath()
        bezier2Path.moveToPoint(CGPointMake(group2.minX + 0.17563 * group2.width, group2.minY + 0.98578 * group2.height))
        bezier2Path.addCurveToPoint(CGPointMake(group2.minX + 0.17563 * group2.width, group2.minY + 0.95261 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.17563 * group2.width, group2.minY + 0.97630 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.17563 * group2.width, group2.minY + 0.96209 * group2.height))
        bezier2Path.addCurveToPoint(CGPointMake(group2.minX + 0.23885 * group2.width, group2.minY + 0.90995 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.17563 * group2.width, group2.minY + 0.92417 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.19670 * group2.width, group2.minY + 0.90995 * group2.height))
        bezier2Path.addCurveToPoint(CGPointMake(group2.minX + 0.38638 * group2.width, group2.minY + 0.90995 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.28803 * group2.width, group2.minY + 0.90995 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.33720 * group2.width, group2.minY + 0.90995 * group2.height))
        bezier2Path.addCurveToPoint(CGPointMake(group2.minX + 0.40043 * group2.width, group2.minY + 0.90047 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.40043 * group2.width, group2.minY + 0.90995 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.40043 * group2.width, group2.minY + 0.90521 * group2.height))
        bezier2Path.addCurveToPoint(CGPointMake(group2.minX + 0.40043 * group2.width, group2.minY + 0.83412 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.40043 * group2.width, group2.minY + 0.87678 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.40043 * group2.width, group2.minY + 0.85782 * group2.height))
        bezier2Path.addCurveToPoint(CGPointMake(group2.minX + 0.38638 * group2.width, group2.minY + 0.82464 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.40043 * group2.width, group2.minY + 0.82938 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.39340 * group2.width, group2.minY + 0.82464 * group2.height))
        bezier2Path.addCurveToPoint(CGPointMake(group2.minX + 0.09133 * group2.width, group2.minY + 0.68720 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.26695 * group2.width, group2.minY + 0.80569 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.16860 * group2.width, group2.minY + 0.75829 * group2.height))
        bezier2Path.addCurveToPoint(CGPointMake(group2.minX + 0.00000 * group2.width, group2.minY + 0.49763 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.03513 * group2.width, group2.minY + 0.63033 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.00000 * group2.width, group2.minY + 0.56398 * group2.height))
        bezier2Path.addCurveToPoint(CGPointMake(group2.minX + 0.00000 * group2.width, group2.minY + 0.45972 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.00000 * group2.width, group2.minY + 0.48341 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.00000 * group2.width, group2.minY + 0.47393 * group2.height))
        bezier2Path.addCurveToPoint(CGPointMake(group2.minX + 0.08430 * group2.width, group2.minY + 0.42654 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.00000 * group2.width, group2.minY + 0.43128 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.04215 * group2.width, group2.minY + 0.41232 * group2.height))
        bezier2Path.addCurveToPoint(CGPointMake(group2.minX + 0.11240 * group2.width, group2.minY + 0.46445 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.10538 * group2.width, group2.minY + 0.43602 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.11240 * group2.width, group2.minY + 0.45024 * group2.height))
        bezier2Path.addCurveToPoint(CGPointMake(group2.minX + 0.11943 * group2.width, group2.minY + 0.54976 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.11240 * group2.width, group2.minY + 0.49289 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.11240 * group2.width, group2.minY + 0.52133 * group2.height))
        bezier2Path.addCurveToPoint(CGPointMake(group2.minX + 0.40043 * group2.width, group2.minY + 0.75355 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.15455 * group2.width, group2.minY + 0.65403 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.24588 * group2.width, group2.minY + 0.72512 * group2.height))
        bezier2Path.addCurveToPoint(CGPointMake(group2.minX + 0.84300 * group2.width, group2.minY + 0.62559 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.57605 * group2.width, group2.minY + 0.78673 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.75870 * group2.width, group2.minY + 0.73460 * group2.height))
        bezier2Path.addCurveToPoint(CGPointMake(group2.minX + 0.89218 * group2.width, group2.minY + 0.49763 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.87813 * group2.width, group2.minY + 0.58768 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.89218 * group2.width, group2.minY + 0.54028 * group2.height))
        bezier2Path.addCurveToPoint(CGPointMake(group2.minX + 0.89218 * group2.width, group2.minY + 0.46445 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.89218 * group2.width, group2.minY + 0.48815 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.89218 * group2.width, group2.minY + 0.47393 * group2.height))
        bezier2Path.addCurveToPoint(CGPointMake(group2.minX + 0.92730 * group2.width, group2.minY + 0.42654 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.89218 * group2.width, group2.minY + 0.45024 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.90623 * group2.width, group2.minY + 0.43602 * group2.height))
        bezier2Path.addCurveToPoint(CGPointMake(group2.minX + 0.98350 * group2.width, group2.minY + 0.43602 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.94838 * group2.width, group2.minY + 0.42180 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.96945 * group2.width, group2.minY + 0.42180 * group2.height))
        bezier2Path.addCurveToPoint(CGPointMake(group2.minX + 0.99755 * group2.width, group2.minY + 0.46445 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.99053 * group2.width, group2.minY + 0.44550 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.99755 * group2.width, group2.minY + 0.45498 * group2.height))
        bezier2Path.addCurveToPoint(CGPointMake(group2.minX + 0.96243 * group2.width, group2.minY + 0.63033 * group2.height), controlPoint1: CGPointMake(group2.minX + 1.00458 * group2.width, group2.minY + 0.52133 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.99755 * group2.width, group2.minY + 0.57346 * group2.height))
        bezier2Path.addCurveToPoint(CGPointMake(group2.minX + 0.80788 * group2.width, group2.minY + 0.76777 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.92730 * group2.width, group2.minY + 0.68720 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.87813 * group2.width, group2.minY + 0.72986 * group2.height))
        bezier2Path.addCurveToPoint(CGPointMake(group2.minX + 0.61820 * group2.width, group2.minY + 0.83412 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.75168 * group2.width, group2.minY + 0.80095 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.68845 * group2.width, group2.minY + 0.81991 * group2.height))
        bezier2Path.addCurveToPoint(CGPointMake(group2.minX + 0.60415 * group2.width, group2.minY + 0.84360 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.61118 * group2.width, group2.minY + 0.83412 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.60415 * group2.width, group2.minY + 0.83886 * group2.height))
        bezier2Path.addCurveToPoint(CGPointMake(group2.minX + 0.60415 * group2.width, group2.minY + 0.91469 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.60415 * group2.width, group2.minY + 0.86730 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.60415 * group2.width, group2.minY + 0.89100 * group2.height))
        bezier2Path.addCurveToPoint(CGPointMake(group2.minX + 0.61820 * group2.width, group2.minY + 0.92417 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.60415 * group2.width, group2.minY + 0.91943 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.61118 * group2.width, group2.minY + 0.92417 * group2.height))
        bezier2Path.addCurveToPoint(CGPointMake(group2.minX + 0.76573 * group2.width, group2.minY + 0.92417 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.66738 * group2.width, group2.minY + 0.92417 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.71655 * group2.width, group2.minY + 0.92417 * group2.height))
        bezier2Path.addCurveToPoint(CGPointMake(group2.minX + 0.82895 * group2.width, group2.minY + 0.96682 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.80788 * group2.width, group2.minY + 0.92417 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.82895 * group2.width, group2.minY + 0.93839 * group2.height))
        bezier2Path.addCurveToPoint(CGPointMake(group2.minX + 0.82895 * group2.width, group2.minY + 1.00000 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.82895 * group2.width, group2.minY + 0.97630 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.82895 * group2.width, group2.minY + 0.99052 * group2.height))
        bezier2Path.addCurveToPoint(CGPointMake(group2.minX + 0.17563 * group2.width, group2.minY + 0.98578 * group2.height), controlPoint1: CGPointMake(group2.minX + 0.62523 * group2.width, group2.minY + 0.98578 * group2.height), controlPoint2: CGPointMake(group2.minX + 0.40043 * group2.width, group2.minY + 0.98578 * group2.height))
        bezier2Path.closePath()
        bezier2Path.miterLimit = 4;

        whiteElement.setFill()
        bezier2Path.fill()
    }

    public class func drawComplete() {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()

        //// Symbol Drawing
        let symbolRect = CGRectMake(-15, -4, 456, 111)
        CGContextSaveGState(context)
        UIRectClip(symbolRect)
        CGContextTranslateCTM(context, symbolRect.origin.x, symbolRect.origin.y)

        CircleBarStyleKit.drawBar(frame: CGRectMake(0, 0, symbolRect.size.width, symbolRect.size.height))
        CGContextRestoreGState(context)


        //// Symbol 2 Drawing
        let symbol2Rect = CGRectMake(173, 12, 80, 80)
        CGContextSaveGState(context)
        UIRectClip(symbol2Rect)
        CGContextTranslateCTM(context, symbol2Rect.origin.x, symbol2Rect.origin.y)

        CircleBarStyleKit.drawButton(frame: CGRectMake(0, 0, symbol2Rect.size.width, symbol2Rect.size.height), highlighted: true)
        CGContextRestoreGState(context)
    }

    public class func drawHLine(frame frame: CGRect = CGRectMake(0, 26, 351, 32)) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()


        //// Shadow Declarations
        let lowShadow = NSShadow()
        lowShadow.shadowColor = UIColor.blackColor()
        lowShadow.shadowOffset = CGSizeMake(0.1, -0.1)
        lowShadow.shadowBlurRadius = 3

        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(frame.minX + 2.5, frame.minY + 15.5))
        bezierPath.addLineToPoint(CGPointMake(frame.maxX - 0.5, frame.minY + 15.5))
        CGContextSaveGState(context)
        CGContextSetShadowWithColor(context, lowShadow.shadowOffset, lowShadow.shadowBlurRadius, (lowShadow.shadowColor as! UIColor).CGColor)
        UIColor.redColor().setStroke()
        bezierPath.lineWidth = 1
        bezierPath.stroke()
        CGContextRestoreGState(context)
    }

    public class func drawCanvas1() {
    }

}
